apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monerod.fullname" . }}
  labels:
    app: {{ include "monerod.name" . }}
    chart: "{{ .Chart.Name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configFile | indent 2 }}